name: cloudreadydata
channels:
  - defaults
  - conda-forge
dependencies:
  - iris=2.3
  - proj4=5
  - ipywidgets
  - zarr
  - ipykernel
  - mo_pack
  - xarray
  - netcdftime
  - azure-storage
  - azure-storage-blob
  - pip
  - dask-kubernetes

